[Desktop Entry]
Name=Arbeit AE Darker
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Arbeit AE Darker
MetacityTheme=Arbeit AE Darker
IconTheme=Faenza
GtkColorScheme=fg_color:#000000,bg_color:#cdcdce,base_color:#FFFFFF,text_color:#1A1A1A,selected_bg_color:#19B2FF,selected_fg_color:#FFFFFF,tooltip_fg_color:#EEEEEE,tooltip_bg_color:#222222
CursorTheme=DMZ-White
CursorSize=18
NotificationTheme=ubuntu
